PREFIX sro: <https://data.vlaanderen.be/ns/slimmeraadpleegomgeving#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?agendaItem ?thema ?label
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # Selecteer alle agendapunten die een thema hebben
    ?agendaItem a besluit:Agendapunt ;
                sro:heeftThema ?thema .

    # Optioneel: haal het label van het thema op
    OPTIONAL {
      ?thema skos:prefLabel ?label .
    }
  }
}
